apiVersion: batch/v1
kind: CronJob
metadata:
  name: market-pricing-job
  namespace: markets-svc-dev
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: market-pricing
            image: quay.io/brbaker/market-pricing:v0.6
            command:
            - /bin/bash
            - "-c"
            - |
                export BASE="--base-currency=EUR"
                export CURRENCIES="--currencies=USD,GBP,JPY,KRW,UAH,THB,TRY,INR,MXN,ILS,AUD,NZD,RUB"
                export UPDATEDAFTER="--updated-after=$(date -d yesterday '+%C%y-%m-%d')"
                export DRYRUN="--dry-run"
                echo $BASE
                echo $CURRENCIES
                echo $UPDATEDAFTER
                echo $DRYRUN
                exec /app/market-pricing-svc $BASE $CURRENCIES $UPDATEDAFTER $DRYRUN
            imagePullPolicy: Always
            volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: app-config        
              items:                  
              - key: "kafka.properties"
                path: "kafka.properties"
              - key: "app-config.properties"
                path: "app-config.properties"
    env:
    - name: BASE
      value: "--base-currency=EUR"
    - name: CURRENCIES
      value: "--currencies=AUD,NZD"
    - name: DRYRUN
      value: "--dry-run"
    - name: UPDATEDAFTER
      value: "--updated-after=2022-09-25"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  kafka.properties: |
    bootstrap.servers=fx-kafka-bootstrap.kafka.svc.cluster.local:9092
    security.protocol=plaintext
    acks=all
  app-config.properties: |
    market-data-publisher=kafka-publisher
    market-data-source=ecb
    reader=one-shot