# Copyright 2022 Bryon Baker

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.apiVersion: apps/v1

apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-pricing
spec:
  replicas: 1
  selector:
    matchLabels:
      application: market-pricing
  template:
    metadata:
      labels:
        application: market-pricing
    spec:
      containers:
      - name: market-pricing
        image: quay.io/brbaker/market-pricing:v0.6
        command:
        - /bin/bash
        - "-c"
        - |
            export BASE="--base-currency=EUR"
            export CURRENCIES="--currencies=USD,GBP,JPY,KRW,UAH,THB,TRY,INR,MXN,ILS,AUD,NZD,RUB"
            export UPDATEDAFTER="--updated-after=$(date -d yesterday '+%C%y-%m-%d')"
            export DRYRUN="--dry-run"
            echo $BASE
            echo $CURRENCIES
            echo $UPDATEDAFTER
            echo $DRYRUN
            exec /app/market-pricing-svc $BASE $CURRENCIES $UPDATEDAFTER $DRYRUN
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: "/app/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: app-config  # Provide the name of the ConfigMap you want to mount.
          items:                  # An array of keys from the ConfigMap to create as files
          - key: "kafka.properties"
            path: "kafka.properties"
          - key: "app-config.properties"
            path: "app-config.properties"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  kafka.properties: |
    bootstrap.servers=fx-pricing-dev-kafka-bootstrap.kafka.svc.cluster.local:9092
    security.protocol=plaintext
    acks=all
  app-config.properties: |
    market-data-publisher=kafka-publisher
    market-data-source=ecb
    reader=one-shot